version: "3"
services:
  db:
    image: "mongo:4.0.4"
    container_name: "db"
    ports:
      - "27017:27017"
    volumes:
      - "../data/db:/data/db"
  api:
    build:
      dockerfile: ../docker/api/Dockerfile
      context: ../api
    depends_on:
      - db
    container_name: "api"
    # restart: unless-stopped
    network_mode: host
    volumes:
      - "../data/load:/data/load"
    # ports:
    #   - "5000:5000"

  web:
    build:
      dockerfile: ../docker/web/Dockerfile
      context: ../web
    container_name: "web"
    depends_on:
      - server
    volumes:
      - "../web/build:/web/build"
    ports:
      - "3000:3000"

  # server:
  #   build:
  #     dockerfile: ./docker/server/Dockerfile
  #     context: ../
  #   container_name: "server"
  #   depends_on:
  #     - api
  #   network_mode: host

  server:
    build:
      dockerfile: ./docker/server/Dockerfile
      context: ../
    container_name: "server"
    volumes:
      - "../nginx.conf:/etc/nginx/nginx.conf"
      - "../web/build:/web/build"
      - "../data/load:/load"
    depends_on:
      - api
    ports:
      - '80:8080'
      - '443:8443'
    # network_mode: host
    # command: /bin/bash -c "envsubst < /etc/nginx/conf.d/mysite.template > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"