version: "3.9"
services:
  db:
    image: mongo:5.0.3
    ports:
      - "27017:27017"
    restart: unless-stopped
    env_file: .env
    environment:
      MONGO_INITDB_DATABASE: admin
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_LOGIN}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - ../data/db:/data/db
      - ../data/logs:/data/logs
      - ../docker/db/mongod.conf:/etc/mongod.conf
    command: --config /etc/mongod.conf

  api:
    build:
      dockerfile: ../docker/api/Dockerfile
      context: ../api
      args:
        - PROTOCOL=${PROTOCOL}
        - HOST=${EXTERNAL_HOST}
        - MODE=${MODE}
        - SIDE_OPTIMIZED=${SIDE_OPTIMIZED}
        - LOCALE=${LOCALE}
        - TIMEZONE=${TIMEZONE}
        - MONGO_DB=${PROJECT_NAME}
        - MONGO_LOGIN=${MONGO_LOGIN}
        - MONGO_PASSWORD=${MONGO_PASSWORD}
        - YOOKASSA_ID=${YOOKASSA_ID}
        - YOOKASSA_KEY=${YOOKASSA_KEY}
        - GOOGLE_ID=${GOOGLE_ID}
        - GOOGLE_SECRET=${GOOGLE_SECRET}
        - TG_TOKEN=${TG_TOKEN}
        - BUG_CHAT=${BUG_CHAT}
        - SMSC_LOGIN=${SMSC_LOGIN}
        - SMSC_PASSWORD=${SMSC_PASSWORD}
        - VK_ID=${VK_ID}
        - VK_SECRET=${VK_SECRET}
        - SUBSCRIPTION_DAY=${SUBSCRIPTION_DAY}
        - SUBSCRIPTION_WEEK=${SUBSCRIPTION_WEEK}
        - SUBSCRIPTION_MONTH=${SUBSCRIPTION_MONTH}
        - SUBSCRIPTION_SEASON=${SUBSCRIPTION_SEASON}
        - SUBSCRIPTION_ACADEMIC_YEAR=${SUBSCRIPTION_ACADEMIC_YEAR}
        - SUBSCRIPTION_YEAR=${SUBSCRIPTION_YEAR}
        - DISCOUNT=${DISCOUNT}
    depends_on:
      - db
    restart: unless-stopped
    env_file: .env
    volumes:
      - ../data/load:/data/load
      - ../data/backup:/backup
      - ../scripts:/scripts
      # NOTE: To provide files
      - type: bind
        source: ../data/logs/api.err
        target: /app.err
      - type: bind
        source: ../data/logs/api.log
        target: /app.log
      # For hot reload
      - ../api/api:/api
      - ../api/app.py:/app.py
    command: uvicorn app:app --host 0.0.0.0 --port 5000 --proxy-headers --reload

  jobs:
    build:
      dockerfile: ../docker/api/Dockerfile
      context: ../api
      args:
        - PROTOCOL=${PROTOCOL}
        - HOST=${EXTERNAL_HOST}
        - MODE=${MODE}
        - SIDE_OPTIMIZED=${SIDE_OPTIMIZED}
        - LOCALE=${LOCALE}
        - TIMEZONE=${TIMEZONE}
        - MONGO_DB=${PROJECT_NAME}
        - MONGO_LOGIN=${MONGO_LOGIN}
        - MONGO_PASSWORD=${MONGO_PASSWORD}
        - YOOKASSA_ID=${YOOKASSA_ID}
        - YOOKASSA_KEY=${YOOKASSA_KEY}
        - GOOGLE_ID=${GOOGLE_ID}
        - GOOGLE_SECRET=${GOOGLE_SECRET}
        - TG_TOKEN=${TG_TOKEN}
        - BUG_CHAT=${BUG_CHAT}
        - SMSC_LOGIN=${SMSC_LOGIN}
        - SMSC_PASSWORD=${SMSC_PASSWORD}
        - VK_ID=${VK_ID}
        - VK_SECRET=${VK_SECRET}
        - SUBSCRIPTION_DAY=${SUBSCRIPTION_DAY}
        - SUBSCRIPTION_WEEK=${SUBSCRIPTION_WEEK}
        - SUBSCRIPTION_MONTH=${SUBSCRIPTION_MONTH}
        - SUBSCRIPTION_SEASON=${SUBSCRIPTION_SEASON}
        - SUBSCRIPTION_ACADEMIC_YEAR=${SUBSCRIPTION_ACADEMIC_YEAR}
        - SUBSCRIPTION_YEAR=${SUBSCRIPTION_YEAR}
        - DISCOUNT=${DISCOUNT}
    depends_on:
      - db
    restart: unless-stopped
    env_file: .env
    volumes:
      # NOTE: To provide files
      - type: bind
        source: ../data/logs/jobs.err
        target: /app.err
      - type: bind
        source: ../data/logs/jobs.log
        target: /app.log
    command: uvicorn jobs:app --host 0.0.0.0 --port 5000 --proxy-headers --reload

  web:
    build:
      dockerfile: ../docker/web/Dockerfile
      context: ../web
      args:
        - PROTOCOL=${PROTOCOL}
        - HOST=${EXTERNAL_HOST}
        - LOCALE=${LOCALE}
        - TIMEZONE=${TIMEZONE}
        - NAME=${NAME}
        - MAIL=${EMAIL}
        - PHONE=${PHONE}
        - SOCIAL=${SOCIAL}
        - GOOGLE_MAP_KEY=${GOOGLE_MAP_KEY}
        - GOOGLE_MAP_LAT=${GOOGLE_MAP_LAT}
        - GOOGLE_MAP_LNG=${GOOGLE_MAP_LNG}
        - GOOGLE_MAP_ZOOM=${GOOGLE_MAP_ZOOM}
        - SUBSCRIPTION_DAY=${SUBSCRIPTION_DAY}
        - SUBSCRIPTION_WEEK=${SUBSCRIPTION_WEEK}
        - SUBSCRIPTION_MONTH=${SUBSCRIPTION_MONTH}
        - SUBSCRIPTION_SEASON=${SUBSCRIPTION_SEASON}
        - SUBSCRIPTION_ACADEMIC_YEAR=${SUBSCRIPTION_ACADEMIC_YEAR}
        - SUBSCRIPTION_YEAR=${SUBSCRIPTION_YEAR}
        - DISCOUNT=${DISCOUNT}
    env_file: .env
    volumes:
      - ../web/public:/public
      # NOTE: src/ cannot be specified, because sets.json will not be generated
      - ../web/src/components:/src/components
      - ../web/src/containers:/src/containers
      - ../web/src/lib:/src/lib
      - ../web/src/App.jsx:/src/App.jsx
      - ../web/src/redus.js:/src/redus.js

  server:
    image: "nginx:1.21.3"
    env_file: .env
    volumes:
      - ../docker/server/nginx.conf:/etc/nginx/nginx.conf
      - ../data/load:/load
      - ../data/logs:/data/logs
    depends_on:
      - api
      - jobs
      - web
    ports:
      - "${EXTERNAL_PORT}:80"
