version: "3"
services:
  db:
    image: "mongo:4.0.4"
    container_name: "db"
    ports:
      - "27017:27017"

  api:
    build:
      dockerfile: ../docker/api/Dockerfile
      context: ../api
    depends_on:
      - db
    container_name: "api"
    # restart: unless-stopped
    network_mode: host
    volumes:
      - "../load:/load"
    # ports:
    #   - "5000:5000"

  # front:
  #   build:
  #     dockerfile: ../docker/front/Dockerfile
  #     context: ../frontend
  #   depends_on:
  #     - api
  #   ports:
  #     - "4200:4200"
  #   networks:
  #     - front_net
  #   volumes:
  #     - ../frontend:/app