version: "3"
services:
  db:
    image: "mongo:4.0.4"
    container_name: "db"
    ports:
      - "27017:27017"
    env_file: .env
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_DB}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_LOGIN}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - "../data/db:/data/db"

  api:
    build:
      dockerfile: ../docker/api/Dockerfile
      context: ../api
    depends_on:
      - db
    container_name: "api"
    # restart: unless-stopped
    network_mode: host
    volumes:
      - "../data/load:/data/load"
    # ports:
    #   - "5000:5000"

  # web:
  #   build:
  #     dockerfile: ../docker/web/Dockerfile
  #     context: ../web
  #   container_name: "web"
  #   depends_on:
  #     - server
  #   volumes:
  #     - "../web/build:/build"
  #   # ports:
  #   #   - "3000:3000"

  server:
    # image: "nginx"
    build:
      dockerfile: ../docker/web/Dockerfile
      context: ../web
    container_name: "server"
    volumes:
      - "../nginx.conf:/etc/nginx/nginx.conf"
      # - "../web/build:/web/build"
      - "../data/load:/load"
    depends_on:
      - api
    ports:
      - '80:80'
      - '443:443'